version: "3.9"
services:
  sql:
    container_name: sql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass1234!
    ports:
      - 1434:1433
  proxy:
    container_name: proxy
    image: proxy:latest
    ports:
      - 9999:80
  moviesapi1:
    container_name: moviesapi1
    image: moviesapi:latest
    ports:
      - 9001:80
    environment:
      - CONNECTION_STRING=Server=sql,1433;Database=movies1;User=sa;Password=Pass1234!;
  moviesapi2:
    container_name: moviesapi2
    image: moviesapi:latest
    ports:
      - 9002:80
    environment:
      - CONNECTION_STRING=Server=sql,1433;Database=movies2;User=sa;Password=Pass1234!;
  